version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      # - ./nginx:default.conf:/usr/local/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
      - laravel

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: econnectcom_test
      MYSQL_USER: econnectcom
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9090:9000"

    networks:
      - laravel

  redis:
    image: redis

volumes:
  logvolume01: {}